apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: apps/cert-manager
  prune: true
  validation: client
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: wge
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 10m0s
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: apps/wge
  prune: true
  validation: client
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: apps/tf-controller
  prune: true
  validation: client
  wait: false
